---
detectors:
  UtilityFunction:
    exclude:
      - 'file_fixture'
      - BaseQueryBuilder#struct_from
  NilCheck:
    exclude:
      - LogRecordValidator#input_presence!
  UncommunicativeVariableName:
    enabled: false
directories:
  "app/validators":
    MissingSafeMethod:
      enabled: false