AllCops:
  TargetRubyVersion: 2.7.5
  Exclude:
      - 'bin/bundle'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**/**'
    - 'spec/**/**'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/**'
    - 'app/models/*'

